const routers = {
    Home: '/',
    News: '/News',
    Menu: '/Menu/Coffee',
    Contact: '/Contact',
    About: '/About',
    Tea: '/Menu/Tea',
    Coffee: '/Menu/Coffee',
    Freeze: '/Menu/Freeze',
    Coffee1: '/Menu/Coffee1',
    News1: '/News/News1',
    Login: '/Login',
    Rigister: '/Rigister',
    AddMenu: '/Admin',
    Account: '/Admin/Account',
    AddAccount: '/Admin/Account/AddAccount',
    EditAccount: '/Admin/Account/EditAccount',
    MenuAdmin: '/Admin/MenuList',
    AddMenu: '/Admin/MenuList/AddMenu',
    // EditMenu:'/Admin/MenuList/EditMenu/:id2/:id1',
    Customer: '/Admin/Customer',
    AddCustomer: '/Admin/Customer/AddCustomer',
    // EditCustomer:'/Admin/Customer/EditCustomer',
    Order: '/Admin/Order',
    OrderPayment: '/order/VnPayReturn',
    NewsAdmin: '/Admin/News',
    AddNews: '/Admin/News/AddNews',
};

export default routers;
