const routers = {
    Home: '/',
    News: '/News',
    Menu: '/Menu/Coffee',
    Contact: '/Contact',
    About: '/About',
    Tea: '/Menu/Tea',
    Coffee: '/Menu/Coffee',
    Freeze: '/Menu/Freeze',
    Coffee1: '/Menu/Coffee1',
    News1: '/News/News1',
    Login: '/Login',
    Rigister: '/Rigister',
    AddMenu: '/Admin',
    Account: '/Admin/Account',
    AddAccount: '/Admin/Account/AddAccount',
    EditAccount: '/Admin/Account/EditAccount',
    ProductAdmin: '/Admin/Product',
    AddProduct: '/Admin/Product/AddProduct',
    // EditMenu:'/Admin/MenuList/EditMenu/:id2/:id1',
    Customer: '/Admin/Customer',
    AddCustomer: '/Admin/Customer/AddCustomer',
    // EditCustomer:'/Admin/Customer/EditCustomer',
    Order: '/Admin/Order',
    OrderPayment: '/order/VnPayReturn',
    NewsAdmin: '/Admin/News',
    Dasboard: '/Admin/Dasboard',
    AddNews: '/Admin/News/AddNews',
    AboutsAdmin: '/Admin/Abouts',
    AddAbouts: '/Admin/News/AddAbouts',
    SibarAdmin: '/Admin/Sibar',
    AddSibar: '/Admin/Sibar/AddSibar',
    MenuAdmin: '/Admin/Menu',
    AddMenu: '/Admin/Menu/AddMenu',
};

export default routers;
