const routers = {
    Home: '/',
    News: '/News',
    Menu: '/Menu',
    Contact: '/Contact',
    About: '/About',
    Tea: '/Menu/:productName',
    // Coffee: '/Menu/:productName',
    // Freeze: '/Menu/:productName',
    // Coffee1: '/Menu/Coffee1',
    News1: '/News/News1',
    Login: '/Login',
    Rigister: '/Rigister',
    AddMenu: '/Admin',
    Account: '/Admin/Account',
    AddAccount: '/Admin/Account/AddAccount',
    EditAccount: '/Admin/Account/EditAccount',
    ProductAdmin: '/Admin/Product',
    AddProduct: '/Admin/Product/AddProduct',
    // EditMenu:'/Admin/MenuList/EditMenu/:id2/:id1',
    Customer: '/Admin/Customer',
    AddCustomer: '/Admin/Customer/AddCustomer',
    // EditCustomer:'/Admin/Customer/EditCustomer',
    Order: '/Admin/Order',
    OrderPayment: '/order/VnPayReturn',
    NewsAdmin: '/Admin/News',
    Dasboard: '/Admin/Dasboard',
    AddNews: '/Admin/News/AddNews',
    AboutsAdmin: '/Admin/Abouts',
    AddAbouts: '/Admin/Abouts/AddAbouts',
    ToppingAdmin: '/Admin/Topping',
    AddTopping: '/Admin/Topping/AddTopping',
    IngredientAdmin: '/Admin/Ingredient',
    AddIngredient: '/Admin/Ingredient/AddIngredient',
    SibarAdmin: '/Admin/Sibar',
    AddSibar: '/Admin/Sibar/AddSibar',
    MenuAdmin: '/Admin/Menu',
    AddMenu: '/Admin/Menu/AddMenu',
    DiscountedAdmin: '/Admin/Discounted',
    AddDiscounted: '/Admin/Discounted/AddDiscounted',
};

export default routers;
